name: golang-ci

on: [push, pull_request]

jobs:

  golang-ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@master
        with:
          go-version: ^1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Get dependencies
        run: go mod tidy
      
      - name: Enable debug log
        run: sed -i 's/false/true/g' config/global.go

      - name: Build
        run: go build -ldflags=-checklinkname=0 -v ./...

      - name: Test
        run: sudo go test -ldflags=-checklinkname=0 $(go list ./...) # ip test needs sudo

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@master
        with:
          go-version: ^1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: latest
