name: golang-ci

on: [push, pull_request]

jobs:

  golang-ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@master
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test $(go list ./...)

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@master
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: latest
